### ISSUE TITLE
Unmute option tab in app

### ISSUE THREAD

**Issue by shreyashdelmade0744** [mueller-ma/MuteReminder#113]
Hi @mueller-ma 
I would like to work on unmute feature in this repo under hactoberfest 
Can you please assign this issue to me ?

Thank You

**Comment by shreyashdelmade0744** [comment]
To main activity and will set to level 8

**Comment by mueller-ma** [comment]
Why 8 and not 7 or 9?

**Comment by shreyashdelmade0744** [comment]
my device has 16 level therefore taking mid value 😃

**Comment by shreyashdelmade0744** [comment]
@mueller-ma 
Can you guide me what exact level of volume to set or anything else ?

**Comment by Maan-Sharma** [comment]
Can I work on it

**Comment by mueller-ma** [comment]
The middle level might be too loud. I don't think it's worth to add such a feature as it's not predictable for the user how loud it gets.
