### ISSUE TITLE
Add option to shown reminder even when ring volume is not muted

### ISSUE THREAD

**Issue by TheDcoder** [mueller-ma/MuteReminder#24]
**Is your feature request related to a problem? Please describe.**

I want to use this app to remind myself when the media volume is not muted regardless of the ring volume.

**Describe the solution you'd like**

Add an option to ignore the state of the ring volume.

**Describe alternatives you've considered**

Forking this app, but I don't want to do that.

**Additional context**

Media is muted most of the time and I only enable it when I want to watch something.

**Comment by yoobi** [comment]
Hello, I'm in the process of doing this feature :)

**Comment by mueller-ma** [comment]
@yoobi Can you check the code of my app https://github.com/mueller-ma/Coffee/ before and implement the PreferenceActivity and Prefs.kt similar here?

**Comment by yoobi** [comment]
Sure, you can assign me #25 as well

**Comment by yoobi** [comment]
Also the repo doesn't have the label Hacktoberfest :)

**Comment by mueller-ma** [comment]
> Also the repo doesn't have the label Hacktoberfest :)

I added the label.
