### ISSUE TITLE
Notification doesn't disappear automatically when pairing Bluetooth earphones 

### ISSUE THREAD

**Issue by MYSK-D25N** [mueller-ma/MuteReminder#68]
**Describe the bug**
If no audio peripherals are connected and the mute reminder is active, pairing with a Bluetooth audio device doesn't remove the notification until you manually adjust the volume.

**To Reproduce**
1. Turn up your volume if it is muted so that the mute reminder is active and visible
2. Connect to an audio peripheral via Bluetooth
3. The mute reminder is still visible until you change the volume

**Expected behavior**
I would assume the notification should hide itself automatically, since it already does that when connecting wired headphones.

**Screenshots**
https://user-images.githubusercontent.com/97309558/219292813-5cc0287b-c5a7-4f2f-afef-867dca3c32fb.mp4

**Device (please complete the following information):**
 - Device: [Poco X3 Pro]
 - Android version: [13]

**Additional context**
Since I use my earbuds quite often I encounter this bug on a regular basis, and the fact that the notification stays up indefinitely means that I have to bump the volume up or down a little as an extra step when connecting them.

**Comment by MYSK-D25N** [comment]
It seems like the reminder also doesn't **reappear** (even though the volume isn't muted) when the Bluetooth device disconnects. Again, manually bumping the volume fixes it.

**Comment by mueller-ma** [comment]
Can you check in the OS settings if the app has all permissions? On my device there's a denied permission "Nearby devices".
When I enable it manually, force stop MuteReminder and start it again, the expected behavior above works.

A permission check needs to be added to MuterReminder, though.

**Comment by MYSK-D25N** [comment]
That seems to be it, yeah. After granting the permissions and rebooting everything works as expected. Honestly didn't think that a permission existed for such thing. Thanks for the help.
