### ISSUE TITLE
Show notification (even when ring is on)

### ISSUE THREAD

**Issue by trymeouteh** [mueller-ma/MuteReminder#75]
**Is your feature request related to a problem? Please describe.**
An app that informs you when speaker volume is not muted

**Describe the solution you'd like**
A setting to allow the notification to appear whenever speaker volume is not muted regardless of ringtone status

**Describe alternatives you've considered**
A setting to toggle this feature

**Additional context**
None

**Comment by mueller-ma** [comment]
This setting does exist since version 2.0.
