### ISSUE TITLE
Japanese mistranslations

### ISSUE THREAD

**Issue by TranslucentFoxHuman** [mueller-ma/MuteReminder#78]
**Is your feature request related to a problem? Please describe.**
I am Japanese. When I update this app, I found Japanese mistranslations in this app. 
For example, this app's name translated to "通知をミュートする", but it means "mute the notifications" in Japanese, not "a notification of mute" or "Mute reminder".

**Describe the solution you'd like**
I have translated strings.xml from a Japanese eyes. If you would like, please apply this to app/src/main/res/values-en/strings.xml..
```
<?xml version="1.0" encoding="utf-8"?>
<!-- Translation instructions can be found in the Readme -->
<resources xmlns:tools="http://schemas.android.com/tools" tools:ignore="MissingTranslation, ExtraTranslation">
    <!-- Common strings -->
    <!-- Feel free to actually translate the title -->
    <string name="app_name">Mute Reminder</string>
    <!-- MainActivity -->
    <string name="main_activity_hint">着信音がミュートされているが、メディア音量がミュートされていない場合に通知を表示します。 この動作は、設定で変更できます。</string>
    <string name="error_no_browser_found">ブラウザが見つかりませんでした</string>
    <string name="permission_button">不足している権限を許可</string>
    <string name="permissions_hint">通知を表示したりイベントに反応したりするには、許可が必要です。例えば、Bluetoothヘッドセットが接続された際のイベントなどです。</string>
    <string name="mute_media">メディア音量をミュート</string>
    <string name="mute_media_failed">ボリュームのミュートに失敗しました</string>
    <!-- Notifications -->
    <string name="notification_reminder_text">メディアはミュートされていません</string>
    <string name="notification_reminder_title">リマインダー</string>
    <string name="notification_background_title">バックグラウンドサービス</string>
    <string name="notification_background_summary">この通知カテゴリを非表示にできます。</string>
    <!-- Settings -->
    <string name="settings">設定</string>
    <string name="general">全般</string>
    <string name="notify_only_when_muted">着信音がミュートされている時にのみ通知</string>
    <string name="about">このアプリケーションについて</string>
    <!-- About menu -->
</resources>
```

**Additional context**
I did not think it necessary to translate even the name of the application into Japanese. 
However, if you think you need to translate the name of the app, you can translate it as "ミュートリマインダー" or "音量ミュートリマインダー". If you want to translate, I would prefer the former.

**Comment by mueller-ma** [comment]
Can you upload your translation in Crowdin? Then I can grant you proofreader rights.

**Comment by TranslucentFoxHuman** [comment]
I did not have an account on Crowdin, so I sent issue here.
I have now created a Crowdin  account and changed the translation.
I am very new to Crowdin, so apologies if I am operating incorrectly.

**Comment by mueller-ma** [comment]
![grafik](https://user-images.githubusercontent.com/22525368/224261736-6c8f35bc-34d8-47ae-a022-e5f434574d72.png)

You can click on this checkmark to approve this translation.

**Comment by mueller-ma** [comment]
Actually you don't need to. I removed the wrong translations. Yours are already in this PR: https://github.com/mueller-ma/MuteReminder/pull/79/files
